#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <dxgi.h>
#include <cstdio>
static const wchar_t* kOptions=L"Software\\NeoCore Games\\Warhammer Martyr\\Options";static HWND g_game=nullptr;static HANDLE g_start=nullptr;static volatile LONG g_stop=0;static volatile LONG64 g_frames=0;
template<class T>static void rel(T*&p){if(p){p->Release();p=nullptr;}}
static LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_GETMINMAXINFO&&l){auto*mm=(MINMAXINFO*)l;mm->ptMaxTrackSize.x=4096;mm->ptMaxTrackSize.y=2160;}return DefWindowProcW(h,m,w,l);}
static bool set_pref(DWORD v){HKEY k=nullptr;DWORD d=0;if(RegCreateKeyExW(HKEY_CURRENT_USER,kOptions,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,&d)!=ERROR_SUCCESS)return false;LONG r=RegSetValueExW(k,L"WindowStyle",0,REG_DWORD,(BYTE*)&v,sizeof(v));RegCloseKey(k);return r==ERROR_SUCCESS;}
static void pump_ms(DWORD ms){DWORD st=GetTickCount();do{MSG m{};while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(1);}while(GetTickCount()-st<ms);}
static DWORD WINAPI Render(LPVOID){WaitForSingleObject(g_start,INFINITE);DXGI_SWAP_CHAIN_DESC sd{};sd.BufferDesc.Width=1280;sd.BufferDesc.Height=720;sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferDesc.RefreshRate.Numerator=60;sd.BufferDesc.RefreshRate.Denominator=1;sd.SampleDesc.Count=1;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.OutputWindow=g_game;sd.Windowed=TRUE;sd.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;ID3D11Device*d=nullptr;ID3D11DeviceContext*c=nullptr;IDXGISwapChain*s=nullptr;D3D_FEATURE_LEVEL fl{};if(FAILED(D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&sd,&s,&d,&fl,&c)))return 10;ID3D11Texture2D*b=nullptr;ID3D11RenderTargetView*r=nullptr;if(FAILED(s->GetBuffer(0,__uuidof(ID3D11Texture2D),(void**)&b))||FAILED(d->CreateRenderTargetView(b,nullptr,&r)))return 11;rel(b);float col[4]={.1f,.2f,.3f,1.f};while(!InterlockedCompareExchange(&g_stop,0,0)){c->OMSetRenderTargets(1,&r,nullptr);c->ClearRenderTargetView(r,col);if(FAILED(s->Present(1,0)))break;InterlockedIncrement64(&g_frames);Sleep(1);}rel(r);rel(s);rel(c);rel(d);return 0;}
int WINAPI wWinMain(HINSTANCE i,HINSTANCE,LPWSTR,int){FILE*f=nullptr;_wfopen_s(&f,L"RC59_NEGATIVE_FIELD_REPLAY.txt",L"wb");if(!f)return 90;set_pref(1);WNDCLASSW wc{};wc.lpfnWndProc=Proc;wc.hInstance=i;wc.lpszClassName=L"PTAR_RC59_NEGATIVE_GAME";RegisterClassW(&wc);DWORD st=WS_POPUP|WS_VISIBLE|WS_CLIPSIBLINGS;g_game=CreateWindowExW(0,wc.lpszClassName,L"Warhammer: Inquisitor - Martyr",st,0,0,1280,720,nullptr,nullptr,i,nullptr);if(!g_game){fclose(f);return 91;}ShowWindow(g_game,SW_SHOW);g_start=CreateEventW(nullptr,TRUE,FALSE,nullptr);HANDLE t=CreateThread(nullptr,0,Render,nullptr,0,nullptr);SetEvent(g_start);Sleep(15000);LONG64 fr=InterlockedCompareExchange64(&g_frames,0,0);HMODULE rt=GetModuleHandleW(L"d3d11.dll");unsigned before=0xff,after=0xff;if(rt){BYTE*b=(BYTE*)rt;before=*(volatile BYTE*)(b+0x034FFA68u);*(volatile BYTE*)(b+0x034FFA68u)=2;MemoryBarrier();after=*(volatile BYTE*)(b+0x034FFA68u);}fwprintf(f,L"RC59_NEGATIVE_STALL_DONE frames=%lld policyBefore=%u policyAfter=%u\n",fr,before,after);fflush(f);pump_ms(2500);InterlockedExchange(&g_stop,1);WaitForSingleObject(t,10000);CloseHandle(t);CloseHandle(g_start);fclose(f);return fr>=10?0:92;}
