#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <dxgi.h>
#include <cstdio>

static const wchar_t* kOptions=L"Software\\NeoCore Games\\Warhammer Martyr\\Options";
static HBRUSH g_brush=nullptr;
struct RegBackup{bool existed=false;DWORD value=0;};
struct Geometry{UINT cw=0,ch=0;LONG_PTR style=0,exstyle=0;RECT outer{},clientScreen{};};
struct BridgeState{UINT size,installed,windowed,usrActive,haveSaved;unsigned long long toWindowed,toBorderless,gameClamps,prefRequests,toggleForwards;LONG savedLeft,savedTop,savedRight,savedBottom;};
using QueryBridgeFn=int (WINAPI*)(BridgeState*);
template<class T>static void rel(T*&p){if(p){p->Release();p=nullptr;}}
static LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_ERASEBKGND){RECT r{};GetClientRect(h,&r);FillRect((HDC)w,&r,g_brush);return 1;}return DefWindowProcW(h,m,w,l);}
static void pump(unsigned ms=1){DWORD st=GetTickCount();do{MSG m{};while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(1);}while(GetTickCount()-st<ms);}
static bool geom(HWND h,Geometry&g){if(!IsWindow(h))return false;RECT c{};if(!GetClientRect(h,&c)||!GetWindowRect(h,&g.outer))return false;POINT a{c.left,c.top},b{c.right,c.bottom};if(!ClientToScreen(h,&a)||!ClientToScreen(h,&b))return false;g.cw=(UINT)(c.right-c.left);g.ch=(UINT)(c.bottom-c.top);g.style=GetWindowLongPtrW(h,GWL_STYLE);g.exstyle=GetWindowLongPtrW(h,GWL_EXSTYLE);g.clientScreen={a.x,a.y,b.x,b.y};return g.cw&&g.ch;}
static bool same(const Geometry&a,const Geometry&b){return a.cw==b.cw&&a.ch==b.ch&&a.style==b.style&&a.exstyle==b.exstyle&&a.outer.left==b.outer.left&&a.outer.top==b.outer.top&&a.outer.right==b.outer.right&&a.outer.bottom==b.outer.bottom&&a.clientScreen.left==b.clientScreen.left&&a.clientScreen.top==b.clientScreen.top&&a.clientScreen.right==b.clientScreen.right&&a.clientScreen.bottom==b.clientScreen.bottom;}
static bool game_windowed(const Geometry&g){return (g.style&WS_POPUP)==0 && (g.style&WS_CAPTION)==WS_CAPTION;}
static void backup(RegBackup&b){HKEY k=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,kOptions,0,KEY_QUERY_VALUE,&k)!=ERROR_SUCCESS)return;DWORD t=0,s=sizeof(b.value);if(RegQueryValueExW(k,L"WindowStyle",nullptr,&t,(BYTE*)&b.value,&s)==ERROR_SUCCESS&&t==REG_DWORD&&s==sizeof(b.value))b.existed=true;RegCloseKey(k);}
static bool set_pref(DWORD v){HKEY k=nullptr;DWORD d=0;if(RegCreateKeyExW(HKEY_CURRENT_USER,kOptions,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,&d)!=ERROR_SUCCESS)return false;LONG r=RegSetValueExW(k,L"WindowStyle",0,REG_DWORD,(BYTE*)&v,sizeof(v));RegCloseKey(k);return r==ERROR_SUCCESS;}
static void restore(const RegBackup&b){HKEY k=nullptr;DWORD d=0;if(RegCreateKeyExW(HKEY_CURRENT_USER,kOptions,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,&d)!=ERROR_SUCCESS)return;if(b.existed)RegSetValueExW(k,L"WindowStyle",0,REG_DWORD,(const BYTE*)&b.value,sizeof(b.value));else RegDeleteValueW(k,L"WindowStyle");RegCloseKey(k);}
static bool f10(HWND h){const LPARAM down=(LPARAM)(1u|(0x44u<<16));const LPARAM up=(LPARAM)(1u|(0x44u<<16)|(1u<<30)|(1u<<31));SendMessageW(h,WM_KEYDOWN,VK_F10,down);pump(1);SendMessageW(h,WM_KEYUP,VK_F10,up);pump(1);return true;}
static HWND wait_presenter(unsigned timeout=20000){DWORD st=GetTickCount();do{HWND h=FindWindowW(L"Win81USRPresenterV041",nullptr);if(h&&IsWindow(h))return h;pump(10);}while(GetTickCount()-st<timeout);return nullptr;}
struct Driver{ID3D11DeviceContext*ctx=nullptr;IDXGISwapChain*swap=nullptr;ID3D11RenderTargetView*rtv=nullptr;const float c[4]={0.19f,0.46f,0.82f,1.0f};bool frame(){ctx->OMSetRenderTargets(1,&rtv,nullptr);ctx->ClearRenderTargetView(rtv,c);HRESULT hr=swap->Present(0,0);pump(2);return SUCCEEDED(hr);}};
static bool query(QueryBridgeFn q,BridgeState&s){s={};s.size=sizeof(s);return q&&q(&s)==0;}
static bool wait_state(Driver&d,QueryBridgeFn q,bool windowed,unsigned timeout=8000){DWORD st=GetTickCount();BridgeState s{};do{if(!d.frame())return false;if(query(q,s)&&s.installed&&((s.windowed!=0)==windowed)&&((s.usrActive==0)==windowed))return true;pump(3);}while(GetTickCount()-st<timeout);return false;}

int WINAPI wWinMain(HINSTANCE inst,HINSTANCE,LPWSTR,int){FILE*ev=nullptr;_wfopen_s(&ev,L"RC58_MODE_BRIDGE_STRESS.txt",L"wb");if(!ev)return 90;RegBackup rb{};backup(rb);if(!set_pref(0)){fclose(ev);return 10;}g_brush=CreateSolidBrush(RGB(25,25,25));WNDCLASSW wc{};wc.lpfnWndProc=Proc;wc.hInstance=inst;wc.hbrBackground=g_brush;wc.lpszClassName=L"PTAR_RC58_BRIDGE_GAME";RegisterClassW(&wc);DWORD style=WS_OVERLAPPEDWINDOW|WS_VISIBLE;RECT wr{0,0,1280,720};AdjustWindowRectEx(&wr,style,FALSE,0);HWND game=CreateWindowExW(0,wc.lpszClassName,L"Warhammer: Inquisitor - Martyr",style,35,25,wr.right-wr.left,wr.bottom-wr.top,nullptr,nullptr,inst,nullptr);if(!game){restore(rb);fclose(ev);return 11;}ShowWindow(game,SW_SHOW);UpdateWindow(game);SetForegroundWindow(game);SetFocus(game);pump(40);
DXGI_SWAP_CHAIN_DESC sd{};sd.BufferDesc.Width=1280;sd.BufferDesc.Height=720;sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferDesc.RefreshRate.Numerator=60;sd.BufferDesc.RefreshRate.Denominator=1;sd.SampleDesc.Count=1;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.OutputWindow=game;sd.Windowed=TRUE;sd.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;ID3D11Device*dev=nullptr;ID3D11DeviceContext*ctx=nullptr;IDXGISwapChain*swap=nullptr;D3D_FEATURE_LEVEL fl{};HRESULT hr=D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&sd,&swap,&dev,&fl,&ctx);if(FAILED(hr)){restore(rb);fclose(ev);return 12;}ID3D11Texture2D*bb=nullptr;ID3D11RenderTargetView*rtv=nullptr;if(FAILED(swap->GetBuffer(0,__uuidof(ID3D11Texture2D),(void**)&bb))||FAILED(dev->CreateRenderTargetView(bb,nullptr,&rtv))){restore(rb);fclose(ev);return 13;}rel(bb);Driver d{ctx,swap,rtv};HWND presenter=wait_presenter();if(!presenter){restore(rb);fclose(ev);return 14;}HMODULE car=nullptr;DWORD st=GetTickCount();do{car=GetModuleHandleW(L"ptar_borderless.dll");if(car)break;d.frame();}while(GetTickCount()-st<10000);if(!car){restore(rb);fclose(ev);return 15;}auto q=(QueryBridgeFn)GetProcAddress(car,"PTAR_RC58_QueryBridge");if(!q){restore(rb);fclose(ev);return 16;}
// WindowStyle=0 must autonomously become GAME DIRECT + exact saved window geometry.
if(!wait_state(d,q,true,15000)){restore(rb);fclose(ev);return 17;}for(unsigned i=0;i<240;++i)if(!d.frame()){restore(rb);fclose(ev);return 18;}Geometry base{},pg{};if(!geom(game,base)||!game_windowed(base)||!geom(presenter,pg)){restore(rb);fclose(ev);return 19;}BridgeState bs{};query(q,bs);fwprintf(ev,L"START_WINDOWED=PASS game=%ux%u presenter=%ux%u clamps=%llu\n",base.cw,base.ch,pg.cw,pg.ch,bs.gameClamps);fflush(ev);
// Verify the game's own setting can drive both modes without native Borderless geometry.
if(!set_pref(1)||!wait_state(d,q,false,8000)){restore(rb);fclose(ev);return 20;}for(unsigned i=0;i<30;++i)if(!d.frame()){restore(rb);fclose(ev);return 21;}if(!geom(presenter,pg)||pg.cw!=1920||pg.ch!=1080){restore(rb);fclose(ev);return 22;}if(!set_pref(0)||!wait_state(d,q,true,8000)){restore(rb);fclose(ev);return 23;}for(unsigned i=0;i<60;++i)if(!d.frame()){restore(rb);fclose(ev);return 24;}Geometry afterPref{};if(!geom(game,afterPref)||!same(afterPref,base)){fwprintf(ev,L"PREF_ROUNDTRIP_GEOMETRY=FAIL\n");restore(rb);fclose(ev);return 25;}fwprintf(ev,L"PREF_ROUNDTRIP=PASS\n");fflush(ev);
constexpr unsigned cycles=500;for(unsigned i=0;i<cycles;++i){
 f10(game);if(!wait_state(d,q,false,3000)){fwprintf(ev,L"FAIL cycle=%u borderless state\n",i);restore(rb);fclose(ev);return 30;}for(unsigned k=0;k<8;++k)if(!d.frame()){restore(rb);fclose(ev);return 31;}if(!geom(presenter,pg)||pg.cw!=1920||pg.ch!=1080){fwprintf(ev,L"FAIL cycle=%u presenter=%ux%u\n",i,pg.cw,pg.ch);restore(rb);fclose(ev);return 32;}
 f10(game);if(!wait_state(d,q,true,3000)){fwprintf(ev,L"FAIL cycle=%u windowed state\n",i);restore(rb);fclose(ev);return 33;}for(unsigned k=0;k<12;++k)if(!d.frame()){restore(rb);fclose(ev);return 34;}Geometry gw{};if(!geom(game,gw)||!same(gw,base)||!game_windowed(gw)){fwprintf(ev,L"FAIL cycle=%u windowed geometry %ux%u\n",i,gw.cw,gw.ch);restore(rb);fclose(ev);return 35;}
}
query(q,bs);Geometry fin{};geom(game,fin);if(!same(fin,base)||!game_windowed(fin)||!bs.windowed||bs.usrActive||bs.toWindowed<cycles+1||bs.toBorderless<cycles+1){fwprintf(ev,L"FINAL=FAIL toW=%llu toB=%llu clamps=%llu\n",bs.toWindowed,bs.toBorderless,bs.gameClamps);restore(rb);fclose(ev);return 40;}fwprintf(ev,L"RC58_MODE_BRIDGE_STRESS=PASS cycles=%u toWindowed=%llu toBorderless=%llu clamps=%llu prefRequests=%llu toggleForwards=%llu finalGame=%ux%u presenter=%ux%u\n",cycles,bs.toWindowed,bs.toBorderless,bs.gameClamps,bs.prefRequests,bs.toggleForwards,fin.cw,fin.ch,pg.cw,pg.ch);fflush(ev);
rel(rtv);rel(swap);rel(ctx);rel(dev);if(g_brush)DeleteObject(g_brush);restore(rb);fclose(ev);return 0;}
