#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <dxgi.h>
#include <cstdio>
#include <cstring>

static const wchar_t* kOptions=L"Software\\NeoCore Games\\Warhammer Martyr\\Options";
static HBRUSH g_brush=nullptr;
struct RegBackup{bool existed=false;DWORD value=0;};
struct ModeState{UINT size,installed,borderlessActive,presenterVisible;ULONG_PTR gameStyle,presenterStyle;unsigned long long transitionsToWindowed,transitionsToBorderless;LONG targetLeft,targetTop,targetRight,targetBottom,windowStylePreference;unsigned long long presenterFollows,gameCoercionClamps,presenterClamps,rejectedWindowSaves;LONG savedLeft,savedTop,savedRight,savedBottom;};
struct SyncState{UINT size,installed,resyncing;unsigned long long presentCalls,mismatchChecks,resyncs,failures,transitionSkips,zeroClientSkips,swapReplacements;UINT hwndW,hwndH,swapW,swapH,cachedW,cachedH;};
struct VirtualState{UINT size,stable,borderlessActive;LONG pendingMode;unsigned long long stablePresents,toggleRequests,toggleApplies,earlyRejects,nativeBorderlessBlocks,registryNormalizations,applyFailures;};
using QueryModeFn=int (WINAPI*)(ModeState*);using QuerySyncFn=int (WINAPI*)(SyncState*);using QueryVirtualFn=int (WINAPI*)(VirtualState*);

struct Geometry{UINT cw=0,ch=0;LONG_PTR style=0,exstyle=0;RECT outer{},clientScreen{};};
static bool same_rect(const RECT&a,const RECT&b){return a.left==b.left&&a.top==b.top&&a.right==b.right&&a.bottom==b.bottom;}
static bool same_game(const Geometry&a,const Geometry&b){return a.cw==b.cw&&a.ch==b.ch&&a.style==b.style&&a.exstyle==b.exstyle&&same_rect(a.outer,b.outer)&&same_rect(a.clientScreen,b.clientScreen);}
static bool geom(HWND h,Geometry&g){if(!IsWindow(h))return false;RECT c{};if(!GetClientRect(h,&c)||!GetWindowRect(h,&g.outer))return false;POINT a{c.left,c.top},b{c.right,c.bottom};if(!ClientToScreen(h,&a)||!ClientToScreen(h,&b)||b.x<=a.x||b.y<=a.y)return false;g.cw=(UINT)(c.right-c.left);g.ch=(UINT)(c.bottom-c.top);g.style=GetWindowLongPtrW(h,GWL_STYLE);g.exstyle=GetWindowLongPtrW(h,GWL_EXSTYLE);g.clientScreen={a.x,a.y,b.x,b.y};return g.cw&&g.ch;}
static bool game_windowed(const Geometry&g){return (g.style&WS_POPUP)==0 && (g.style&WS_CAPTION)==WS_CAPTION;}
static LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_ERASEBKGND){RECT r{};GetClientRect(h,&r);FillRect((HDC)w,&r,g_brush);return 1;}return DefWindowProcW(h,m,w,l);}
static void pump(unsigned ms=1){DWORD st=GetTickCount();do{MSG m{};while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(1);}while(GetTickCount()-st<ms);}
static void backup_pref(RegBackup&b){HKEY k=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,kOptions,0,KEY_QUERY_VALUE,&k)!=ERROR_SUCCESS)return;DWORD t=0,s=sizeof(b.value);if(RegQueryValueExW(k,L"WindowStyle",nullptr,&t,(BYTE*)&b.value,&s)==ERROR_SUCCESS&&t==REG_DWORD&&s==sizeof(b.value))b.existed=true;RegCloseKey(k);}
static bool set_pref(DWORD v){HKEY k=nullptr;DWORD d=0;if(RegCreateKeyExW(HKEY_CURRENT_USER,kOptions,0,nullptr,0,KEY_QUERY_VALUE|KEY_SET_VALUE,nullptr,&k,&d)!=ERROR_SUCCESS)return false;LONG r=RegSetValueExW(k,L"WindowStyle",0,REG_DWORD,(BYTE*)&v,sizeof(v));RegCloseKey(k);return r==ERROR_SUCCESS;}
static int get_pref(){HKEY k=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,kOptions,0,KEY_QUERY_VALUE,&k)!=ERROR_SUCCESS)return -1;DWORD t=0,v=0,s=sizeof(v);LONG r=RegQueryValueExW(k,L"WindowStyle",nullptr,&t,(BYTE*)&v,&s);RegCloseKey(k);return (r==ERROR_SUCCESS&&t==REG_DWORD&&s==sizeof(v))?(int)v:-1;}
static void restore_pref(const RegBackup&b){HKEY k=nullptr;DWORD d=0;if(RegCreateKeyExW(HKEY_CURRENT_USER,kOptions,0,nullptr,0,KEY_SET_VALUE,nullptr,&k,&d)!=ERROR_SUCCESS)return;if(b.existed)RegSetValueExW(k,L"WindowStyle",0,REG_DWORD,(const BYTE*)&b.value,sizeof(b.value));else RegDeleteValueW(k,L"WindowStyle");RegCloseKey(k);}
template<class T>static void rel(T*&p){if(p){p->Release();p=nullptr;}}
static HWND wait_presenter(unsigned timeout=15000){DWORD st=GetTickCount();do{HWND h=FindWindowW(L"Win81USRPresenterV041",nullptr);if(h&&IsWindow(h))return h;pump(5);}while(GetTickCount()-st<timeout);return nullptr;}

struct Driver{ID3D11DeviceContext*ctx=nullptr;IDXGISwapChain*swap=nullptr;ID3D11RenderTargetView*rtv=nullptr;const float color[4]={0.13f,0.51f,0.83f,1.0f};bool frame(){ctx->OMSetRenderTargets(1,&rtv,nullptr);ctx->ClearRenderTargetView(rtv,color);HRESULT hr=swap->Present(0,0);pump(2);return SUCCEEDED(hr);}};
static bool press_ctrl_f10(HWND game){SetForegroundWindow(game);SetFocus(game);keybd_event(VK_CONTROL,0,0,0);pump(3);keybd_event(VK_F10,0,0,0);pump(4);keybd_event(VK_F10,0,KEYEVENTF_KEYUP,0);pump(2);keybd_event(VK_CONTROL,0,KEYEVENTF_KEYUP,0);pump(4);return true;}
static bool query(QueryModeFn qm,QuerySyncFn qs,QueryVirtualFn qv,ModeState&m,SyncState&s,VirtualState&v){m={};m.size=sizeof(m);s={};s.size=sizeof(s);v={};v.size=sizeof(v);return qm(&m)==0&&qs(&s)==0&&qv(&v)==0;}

static bool wait_installed(Driver&d,QueryModeFn qm,QuerySyncFn qs,QueryVirtualFn qv,FILE*f,unsigned timeout=20000){DWORD st=GetTickCount();ModeState m{};SyncState s{};VirtualState v{};do{if(!d.frame())return false;if(query(qm,qs,qv,m,s,v)&&m.installed&&s.installed){fwprintf(f,L"INSTALLED=PASS presents=%llu stable=%u\n",s.presentCalls,v.stable);fflush(f);return true;}pump(10);}while(GetTickCount()-st<timeout);return false;}
static bool wait_stable(Driver&d,QueryModeFn qm,QuerySyncFn qs,QueryVirtualFn qv,FILE*f,unsigned timeout=30000){DWORD st=GetTickCount();ModeState m{};SyncState s{};VirtualState v{};do{if(!d.frame())return false;if(query(qm,qs,qv,m,s,v)&&v.stable&&v.stablePresents>=180&&s.failures==0&&v.applyFailures==0){fwprintf(f,L"STABLE=PASS stablePresents=%llu syncPresents=%llu age=%lu\n",v.stablePresents,s.presentCalls,(unsigned long)(GetTickCount()-st));fflush(f);return true;}pump(5);}while(GetTickCount()-st<timeout);fwprintf(f,L"STABLE=FAIL stable=%u stablePresents=%llu syncFailures=%llu applyFailures=%llu\n",v.stable,v.stablePresents,s.failures,v.applyFailures);return false;}
static bool wait_mode(Driver&d,QueryModeFn qm,QuerySyncFn qs,QueryVirtualFn qv,HWND game,HWND presenter,bool borderless,const Geometry&gameBase,FILE*f,unsigned timeout=8000){DWORD st=GetTickCount();ModeState m{};SyncState s{};VirtualState v{};Geometry gg{},pg{};do{if(!d.frame())return false;if(!query(qm,qs,qv,m,s,v)||!geom(game,gg)||!geom(presenter,pg))return false;const bool vis=borderless?(pg.cw==1920&&pg.ch==1080):(pg.cw==gameBase.cw&&pg.ch==gameBase.ch&&same_rect(pg.clientScreen,gameBase.clientScreen));if(v.stable&&((v.borderlessActive!=0)==borderless)&&((m.borderlessActive!=0)==borderless)&&vis&&same_game(gg,gameBase)&&game_windowed(gg)&&s.failures==0&&v.applyFailures==0&&v.pendingMode==-1&&get_pref()==0)return true;pump(5);}while(GetTickCount()-st<timeout);fwprintf(f,L"MODE_FAIL want=%u actualV=%u actualM=%u pending=%ld gameSame=%u game=%ux%u presenter=%ux%u syncFail=%llu applyFail=%llu pref=%d\n",borderless?1u:0u,v.borderlessActive,m.borderlessActive,v.pendingMode,same_game(gg,gameBase)?1u:0u,gg.cw,gg.ch,pg.cw,pg.ch,s.failures,v.applyFailures,get_pref());fflush(f);return false;}

int WINAPI wWinMain(HINSTANCE inst,HINSTANCE,LPWSTR,int){FILE*f=nullptr;_wfopen_s(&f,L"RC58_VIRTUAL_MODE_STRESS.txt",L"wb");if(!f)return 90;RegBackup rb{};backup_pref(rb);if(!set_pref(0)){fclose(f);return 10;}g_brush=CreateSolidBrush(RGB(20,20,20));WNDCLASSW wc{};wc.lpfnWndProc=Proc;wc.hInstance=inst;wc.hbrBackground=g_brush;wc.lpszClassName=L"PTAR_RC58_VIRTUAL_GAME";RegisterClassW(&wc);DWORD style=WS_OVERLAPPEDWINDOW|WS_VISIBLE;RECT wr{0,0,1280,720};AdjustWindowRectEx(&wr,style,FALSE,0);HWND game=CreateWindowExW(0,wc.lpszClassName,L"Warhammer: Inquisitor - Martyr",style,20,20,wr.right-wr.left,wr.bottom-wr.top,nullptr,nullptr,inst,nullptr);if(!game){restore_pref(rb);fclose(f);return 11;}ShowWindow(game,SW_SHOW);UpdateWindow(game);pump(30);
DXGI_SWAP_CHAIN_DESC sd{};sd.BufferDesc.Width=1280;sd.BufferDesc.Height=720;sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferDesc.RefreshRate.Numerator=60;sd.BufferDesc.RefreshRate.Denominator=1;sd.SampleDesc.Count=1;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.OutputWindow=game;sd.Windowed=TRUE;sd.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;ID3D11Device*dev=nullptr;ID3D11DeviceContext*ctx=nullptr;IDXGISwapChain*swap=nullptr;D3D_FEATURE_LEVEL fl{};HRESULT hr=D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&sd,&swap,&dev,&fl,&ctx);if(FAILED(hr)){restore_pref(rb);fclose(f);return 12;}ID3D11Texture2D*bb=nullptr;ID3D11RenderTargetView*rtv=nullptr;if(FAILED(swap->GetBuffer(0,__uuidof(ID3D11Texture2D),(void**)&bb))||FAILED(dev->CreateRenderTargetView(bb,nullptr,&rtv))){restore_pref(rb);fclose(f);return 13;}rel(bb);Driver d{ctx,swap,rtv};for(unsigned i=0;i<40;++i)if(!d.frame()){restore_pref(rb);fclose(f);return 14;}HWND presenter=wait_presenter();HMODULE carrier=GetModuleHandleW(L"ptar_borderless.dll");if(!presenter||!carrier){restore_pref(rb);fclose(f);return 15;}auto qm=(QueryModeFn)GetProcAddress(carrier,"PTAR_BorderlessQueryMode");auto qs=(QuerySyncFn)GetProcAddress(carrier,"PTAR_RC51_QueryPresenterSync");auto qv=(QueryVirtualFn)GetProcAddress(carrier,"PTAR_RC58_QueryVirtualMode");if(!qm||!qs||!qv){restore_pref(rb);fclose(f);return 16;}if(!wait_installed(d,qm,qs,qv,f)){restore_pref(rb);fclose(f);return 17;}
// Early toggle must be consumed but never applied before the startup barrier.
VirtualState before{};ModeState bm{};SyncState bs{};query(qm,qs,qv,bm,bs,before);press_ctrl_f10(game);for(unsigned i=0;i<20;++i)if(!d.frame()){restore_pref(rb);fclose(f);return 18;}VirtualState early{};ModeState em{};SyncState es{};query(qm,qs,qv,em,es,early);if(early.borderlessActive||early.earlyRejects<=before.earlyRejects){fwprintf(f,L"EARLY_BARRIER=FAIL before=%llu after=%llu mode=%u\n",before.earlyRejects,early.earlyRejects,early.borderlessActive);restore_pref(rb);fclose(f);return 19;}fwprintf(f,L"EARLY_BARRIER=PASS rejects=%llu\n",early.earlyRejects);fflush(f);
if(!wait_stable(d,qm,qs,qv,f)){restore_pref(rb);fclose(f);return 20;}Geometry base{};if(!geom(game,base)||!game_windowed(base)){restore_pref(rb);fclose(f);return 21;}ModeState m{};SyncState s{};VirtualState v{};query(qm,qs,qv,m,s,v);if(v.borderlessActive||get_pref()!=0){restore_pref(rb);fclose(f);return 22;}
// First real transition in each direction.
press_ctrl_f10(game);if(!wait_mode(d,qm,qs,qv,game,presenter,true,base,f)){restore_pref(rb);fclose(f);return 23;}press_ctrl_f10(game);if(!wait_mode(d,qm,qs,qv,game,presenter,false,base,f)){restore_pref(rb);fclose(f);return 24;}
constexpr unsigned cycles=500;for(unsigned i=0;i<cycles;++i){press_ctrl_f10(game);if(!wait_mode(d,qm,qs,qv,game,presenter,true,base,f,5000)){fwprintf(f,L"FAIL_CYCLE=%u phase=B\n",i);restore_pref(rb);fclose(f);return 30;}press_ctrl_f10(game);if(!wait_mode(d,qm,qs,qv,game,presenter,false,base,f,5000)){fwprintf(f,L"FAIL_CYCLE=%u phase=W\n",i);restore_pref(rb);fclose(f);return 31;}}
query(qm,qs,qv,m,s,v);Geometry finalg{};geom(game,finalg);if(!same_game(base,finalg)||!game_windowed(finalg)||v.borderlessActive||v.toggleApplies<cycles*2u+2u||s.failures||v.applyFailures||get_pref()!=0){fwprintf(f,L"FINAL=FAIL applies=%llu syncFail=%llu applyFail=%llu pref=%d\n",v.toggleApplies,s.failures,v.applyFailures,get_pref());restore_pref(rb);fclose(f);return 32;}fwprintf(f,L"RC58_VIRTUAL_MODE_STRESS=PASS cycles=%u applies=%llu requests=%llu earlyRejects=%llu game_untouched=1 native_windowed=1 registry0=1 syncFailures=%llu applyFailures=%llu\n",cycles,v.toggleApplies,v.toggleRequests,v.earlyRejects,s.failures,v.applyFailures);fflush(f);
rel(rtv);rel(swap);rel(ctx);rel(dev);if(g_brush)DeleteObject(g_brush);restore_pref(rb);fclose(f);return 0;}
