#!/usr/bin/env python3
"""LAB16: post-freeze fresh validation of the frozen LAB15 outer-balance router.

This is a validation protocol, not a tuning sweep. The LAB15 candidate was
frozen before this generator was authored. Every HR reference in this script
is newly generated by deterministic analytic/procedural definitions. LR input
uses the exact PTAR-PERCEPTUAL-V1-A downsample contract:
  skimage.transform.resize, order=3, mode='reflect', anti_aliasing=True,
  preserve_range=True, clip=True, sRGB/code-value domain.

After the first observed LAB16 result, neither candidate parameters nor gates
in this file may be changed to improve LAB16. A failed gate rejects this frozen
candidate; a later candidate requires another fresh validation set.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path

import numpy as np
import skimage
from skimage.transform import resize

import lab_moe_ng_v02_outer_balance as q15
import lab_moe_ng_v02_v01_quality as q10

HR_H = 288
HR_W = 288
LR_H = 192
LR_W = 192
SCALE = 1.5
SEED = 16091531
EXPECTED_SKIMAGE = "0.26.0"

FROZEN_EXPECTED = {
    "protocol": "LAB15_FROZEN_OUTER_BALANCE_CANDIDATE",
    "frozen_from_commit": "6c7869bfb927bd4fc7abcbf17203b38b0290d29c",
    "selection_run_id": 34227242075,
    "selection_artifact_sha256": "f7ffbaed09bd98cf871e5a22348aab1c1b9d2cc5ac88f4421a0514278fc9efa5",
    "candidate": {"kind": "bal_noturn", "bal_t": 0.15, "bal_w": 0.10, "strength": 0.50},
    "texture_fetch_delta": 0,
}

# Frozen before the first LAB16 run. Do not relax these after observing LAB16.
GATES = {
    "overall_mean_gap_v01_db_min": 0.05,
    "overall_worst_gap_v01_db_min": -0.20,
    "structural_mean_gap_v01_db_min": -0.03,
    "structural_worst_gap_v01_db_min": -0.20,
    "texture_mean_gap_v01_db_min": 0.10,
}

STRUCTURAL_FAMILIES = {
    "fresh_slanted_strokes",
    "fresh_junctions",
    "fresh_glyph_stencil",
}
TEXTURE_FAMILIES = {
    "fresh_frequency_chirp",
    "fresh_anisotropic_texture",
    "fresh_microtexture_gradient",
}


def clip01(x):
    return np.clip(x, np.float32(0), np.float32(1)).astype(np.float32)


def smoothstep01(x):
    x = np.clip(x, 0.0, 1.0)
    return x * x * (3.0 - 2.0 * x)


def band(dist, half_width, aa=0.85):
    x = (float(half_width) + float(aa) - np.abs(dist)) / (2.0 * float(aa))
    return smoothstep01(x).astype(np.float32)


def rgb_from_luma(y, chroma_a=0.0, chroma_b=0.0):
    y = np.asarray(y, dtype=np.float32)
    r = y + np.float32(chroma_a)
    g = y - np.float32(0.35 * chroma_a) + np.float32(0.15 * chroma_b)
    b = y + np.float32(chroma_b)
    return clip01(np.stack((r, g, b), axis=2))


def coords():
    yy, xx = np.mgrid[0:HR_H, 0:HR_W]
    x = xx.astype(np.float32) - np.float32((HR_W - 1) * 0.5)
    y = yy.astype(np.float32) - np.float32((HR_H - 1) * 0.5)
    return x, y


def make_slanted(case_index):
    x, y = coords()
    angles = [17.0, 29.0, 41.0, 53.0, 67.0, 76.0]
    widths = [1.25, 1.55, 1.90, 2.20, 2.55, 2.90]
    phases = [-0.43, 0.31, -0.17, 0.47, -0.29, 0.13]
    th = np.deg2rad(angles[case_index])
    n = x * np.float32(math.cos(th)) + y * np.float32(math.sin(th))
    offset = np.float32(phases[case_index])
    stripe = np.zeros((HR_H, HR_W), dtype=np.float32)
    for k, pos in enumerate((-73.0, -24.0, 25.0, 74.0)):
        w = widths[case_index] * (1.0 + 0.10 * ((k + case_index) % 3 - 1))
        stripe = np.maximum(stripe, band(n - np.float32(pos) - offset, 0.5 * w))
    bg = np.float32(0.16) + np.float32(0.10) * (x / np.float32(HR_W))
    lum = bg * (np.float32(1) - stripe) + np.float32(0.88) * stripe
    return rgb_from_luma(lum, 0.025 * ((case_index % 3) - 1), -0.018 * ((case_index + 1) % 3 - 1))


def rect_mask(x, y, cx, cy, hx, hy, aa=0.85):
    dx = np.abs(x - np.float32(cx)) - np.float32(hx)
    dy = np.abs(y - np.float32(cy)) - np.float32(hy)
    outside = np.maximum(dx, dy)
    return smoothstep01((float(aa) - outside) / (2.0 * float(aa))).astype(np.float32)


def make_junction(case_index):
    x, y = coords()
    shift = [-0.41, 0.23, 0.49, -0.28, 0.11, -0.37][case_index]
    w = [1.4, 1.8, 2.2, 2.6, 1.6, 2.4][case_index]
    m = np.zeros((HR_H, HR_W), dtype=np.float32)
    if case_index == 0:
        m = np.maximum(rect_mask(x, y, -30+shift, 0, w, 88), rect_mask(x, y, 16, 48+shift, 48, w))
    elif case_index == 1:
        m = np.maximum(rect_mask(x, y, 0+shift, 12, w, 92), rect_mask(x, y, 0, -48+shift, 68, w))
    elif case_index == 2:
        m = np.maximum(rect_mask(x, y, shift, 0, w, 100), rect_mask(x, y, 0, shift, 104, w))
    elif case_index == 3:
        for k in range(6):
            m = np.maximum(m, rect_mask(x, y, -78 + 28*k + shift, 68 - 24*k, 15, w))
            m = np.maximum(m, rect_mask(x, y, -63 + 28*k, 56 - 24*k + shift, w, 13))
    elif case_index == 4:
        for cx, cy in [(-58,-44),(0,-8),(56,42)]:
            m = np.maximum(m, rect_mask(x, y, cx+shift, cy, w, 35))
            m = np.maximum(m, rect_mask(x, y, cx+18, cy+34+shift, 18, w))
    else:
        m = np.maximum(rect_mask(x, y, -34+shift, 0, w, 96), rect_mask(x, y, 34-shift, 0, w, 96))
        m = np.maximum(m, rect_mask(x, y, 0, -61+shift, 36, w))
        m = np.maximum(m, rect_mask(x, y, 0, 61-shift, 36, w))
    grad = np.float32(0.12) + np.float32(0.06) * (y / np.float32(HR_H))
    lum = grad * (np.float32(1)-m) + np.float32(0.91) * m
    return rgb_from_luma(lum, -0.018 + 0.006*case_index, 0.012 - 0.004*case_index)


def ellipse_edge(x, y, cx, cy, rx, ry, width):
    ux = (x - np.float32(cx)) / np.float32(rx)
    uy = (y - np.float32(cy)) / np.float32(ry)
    r = np.sqrt(ux*ux + uy*uy)
    scale = np.float32(min(rx, ry))
    return band((r - np.float32(1.0)) * scale, 0.5 * width)


def make_glyph(case_index):
    x, y = coords()
    phase = [-0.37, 0.19, 0.43, -0.21, 0.08, -0.46][case_index]
    w = [1.35, 1.65, 1.95, 2.25, 1.50, 2.05][case_index]
    m = np.zeros((HR_H, HR_W), dtype=np.float32)
    positions = (-72, 0, 72)
    for j, cx in enumerate(positions):
        kind = (case_index + j) % 3
        if kind == 0:
            m = np.maximum(m, rect_mask(x, y, cx-15+phase, 0, w, 48))
            m = np.maximum(m, ellipse_edge(x, y, cx+5, -18+phase, 23, 29, w*1.1))
        elif kind == 1:
            m = np.maximum(m, rect_mask(x, y, cx+phase, 0, w, 50))
            m = np.maximum(m, rect_mask(x, y, cx+18, -48+phase, 19, w))
            m = np.maximum(m, rect_mask(x, y, cx+18, 0-phase, 19, w))
        else:
            m = np.maximum(m, ellipse_edge(x, y, cx+phase, 0, 28, 48, w))
            cut = rect_mask(x, y, cx+27, 0, 13, 22, 0.7)
            m = m * (np.float32(1)-cut)
    lum = np.float32(0.14) + np.float32(0.78) * m
    return rgb_from_luma(lum, 0.014*((case_index%2)*2-1), -0.011*((case_index//2)%2*2-1))


def make_chirp(case_index):
    x, y = coords()
    xn=x/np.float32(HR_W); yn=y/np.float32(HR_H)
    a=[0.72,0.91,1.13,1.37,1.61,1.87][case_index]
    b=[1.51,1.23,0.97,1.79,1.31,1.07][case_index]
    phi=[0.13,0.47,0.81,1.19,1.61,2.03][case_index]
    r2=xn*xn+yn*yn
    p1=np.sin(np.float32(2*math.pi)*(np.float32(9.7*a)*xn + np.float32(6.3*b)*yn + np.float32(21.0)*r2)+np.float32(phi))
    p2=np.sin(np.float32(2*math.pi)*(np.float32(-5.4*b)*xn + np.float32(13.1*a)*yn + np.float32(11.0)*r2)-np.float32(phi*.7))
    env=np.float32(0.72)+np.float32(0.28)*np.cos(np.float32(2*math.pi)*(np.float32(.37)*xn-np.float32(.29)*yn))
    lum=np.float32(.50)+np.float32(.205)*p1*env+np.float32(.135)*p2
    return rgb_from_luma(lum, 0.010*np.sin(phi), -0.012*np.cos(phi))


def make_aniso(case_index):
    x,y=coords(); xn=x/np.float32(HR_W); yn=y/np.float32(HR_H)
    rng=np.random.default_rng(SEED + 101*case_index)
    acc=np.zeros((HR_H,HR_W),dtype=np.float32)
    norm=0.0
    for octave in range(8):
        angle=float(rng.uniform(0.0,math.pi))
        freq=float(rng.uniform(4.5,20.0))*(1.0+0.07*octave)
        phase=float(rng.uniform(0.0,2*math.pi))
        weight=1.0/(1.0+0.32*octave)
        proj=xn*np.float32(math.cos(angle))+yn*np.float32(math.sin(angle))
        warp=np.float32(0.11)*np.sin(np.float32(2*math.pi)*(yn*np.float32(1.3+0.17*octave)+np.float32(phase*.13)))
        acc += np.float32(weight)*np.sin(np.float32(2*math.pi*freq)*(proj+warp)+np.float32(phase))
        norm += weight
    acc/=np.float32(norm)
    ridge=np.tanh(np.float32(1.35)*acc).astype(np.float32)
    lum=np.float32(.48)+np.float32(.34)*ridge+np.float32(.07)*(xn-yn)
    return rgb_from_luma(lum, 0.013*((case_index%3)-1), 0.009*((case_index%2)*2-1))


def make_microgradient(case_index):
    x,y=coords(); xn=x/np.float32(HR_W); yn=y/np.float32(HR_H)
    phase=np.float32([.11,.37,.59,.83,1.07,1.31][case_index])
    grad=np.float32(.46)+np.float32(.20)*xn-np.float32(.15)*yn+np.float32(.06)*xn*yn
    f1=np.float32(15.3+1.7*case_index); f2=np.float32(11.7+2.1*((case_index+2)%6))
    micro=np.sin(np.float32(2*math.pi)*(f1*xn+np.float32(.37)*f2*yn)+phase)
    micro+=np.float32(.63)*np.sin(np.float32(2*math.pi)*(-np.float32(.41)*f1*xn+f2*yn)-phase*np.float32(.73))
    oblique=x*np.float32(math.cos(.61+.07*case_index))+y*np.float32(math.sin(.61+.07*case_index))
    edge=np.zeros((HR_H,HR_W),dtype=np.float32)
    for p in (-91.0,-37.0,19.0,83.0):
        edge=np.maximum(edge,band(oblique-np.float32(p)-phase,0.65+0.10*(case_index%3),0.75))
    lum=grad+np.float32(.085)*micro+np.float32(.14)*edge
    return rgb_from_luma(lum, -0.008+0.003*case_index, 0.010-0.002*case_index)


GENERATORS = [
    ("fresh_slanted_strokes", "structural", make_slanted),
    ("fresh_junctions", "structural", make_junction),
    ("fresh_glyph_stencil", "structural", make_glyph),
    ("fresh_frequency_chirp", "texture", make_chirp),
    ("fresh_anisotropic_texture", "texture", make_aniso),
    ("fresh_microtexture_gradient", "texture", make_microgradient),
]


def downsample(hr):
    out=resize(
        hr,
        (LR_H,LR_W,3),
        order=3,
        mode="reflect",
        anti_aliasing=True,
        preserve_range=True,
        clip=True,
    )
    return np.asarray(out,dtype=np.float32)


def psnr(a,b):
    d=np.asarray(a,dtype=np.float64)-np.asarray(b,dtype=np.float64)
    mse=float(np.mean(d*d,dtype=np.float64))
    return float("inf") if mse<=0 else 10.0*math.log10(1.0/mse)


def sha256_array(a):
    x=np.ascontiguousarray(np.asarray(a,dtype=np.float32))
    return hashlib.sha256(x.tobytes(order="C")).hexdigest()


def validate_frozen(path):
    raw=path.read_bytes(); cfg=json.loads(raw.decode("utf-8"))
    for k in ("protocol","frozen_from_commit","selection_run_id","selection_artifact_sha256","texture_fetch_delta"):
        if cfg.get(k)!=FROZEN_EXPECTED[k]:
            raise RuntimeError(f"frozen candidate mismatch: {k}: {cfg.get(k)!r}")
    if cfg.get("candidate")!=FROZEN_EXPECTED["candidate"]:
        raise RuntimeError(f"frozen candidate parameters changed: {cfg.get('candidate')!r}")
    policy=cfg.get("freeze_policy",{})
    required={"immutable_for_next_validation":True,"no_parameter_change_after_LAB16_observation":True,"LAB16_must_be_created_after_this_freeze_commit":True,"LAB16_is_validation_not_tuning":True}
    if any(policy.get(k)!=v for k,v in required.items()):
        raise RuntimeError("frozen validation policy changed")
    return cfg,hashlib.sha256(raw).hexdigest()


def block(rows):
    gaps=[r["gap_v01_db"] for r in rows]
    return {
        "cases":len(rows),
        "mean_gap_v01_db":float(np.mean(gaps,dtype=np.float64)),
        "worst_gap_v01_db":float(np.min(gaps)),
        "wins_v01":int(sum(x>0 for x in gaps)),
        "mean_gate":float(np.mean([r["gate_mean"] for r in rows],dtype=np.float64)),
    }


def write_csv(path,rows):
    with path.open("w",newline="",encoding="utf-8") as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--frozen",default="lab_protocols/LAB15_FROZEN_CANDIDATE.json")
    ap.add_argument("--out",required=True)
    a=ap.parse_args()
    out=Path(a.out); out.mkdir(parents=True,exist_ok=True)

    if skimage.__version__!=EXPECTED_SKIMAGE:
        raise RuntimeError(f"LAB16 requires scikit-image {EXPECTED_SKIMAGE}, got {skimage.__version__}")
    frozen,frozen_sha256=validate_frozen(Path(a.frozen))
    spec=frozen["candidate"]

    rows=[]; manifest=[]
    for family,group,fn in GENERATORS:
        for i in range(6):
            case_id=f"LAB16-{family.upper().replace('FRESH_','')}-{i+1:02d}"
            hr=clip01(fn(i))
            if hr.shape!=(HR_H,HR_W,3) or not np.isfinite(hr).all():
                raise RuntimeError(f"invalid HR generator output: {case_id}")
            lr=downsample(hr)
            if lr.shape!=(LR_H,LR_W,3) or not np.isfinite(lr).all():
                raise RuntimeError(f"invalid LR input: {case_id}")
            v01,v02=q10.reconstruct_pair(lr)
            if v01.shape!=hr.shape or v02.shape!=hr.shape:
                raise RuntimeError(f"x1.5 geometry mismatch: {case_id}: {v01.shape}/{v02.shape}/{hr.shape}")
            feat=q15.features15(lr); g=q15.gate(feat,spec)
            hybrid=np.clip(v01+(v02-v01)*g,np.float32(0),np.float32(1)).astype(np.float32)
            if hybrid.shape!=hr.shape or not np.isfinite(hybrid).all():
                raise RuntimeError(f"invalid hybrid output: {case_id}")
            if float(np.min(hybrid))<0.0 or float(np.max(hybrid))>1.0:
                raise RuntimeError(f"hybrid range violation: {case_id}")
            p01=psnr(v01,hr); p02=psnr(v02,hr); ph=psnr(hybrid,hr)
            row={
                "case_id":case_id,"family":family,"group":group,
                "v01_psnr_db":p01,"v02_mc_psnr_db":p02,"hybrid_psnr_db":ph,
                "gap_v01_db":ph-p01,"gap_v02_db":ph-p02,
                "gate_mean":float(np.mean(g,dtype=np.float64)),
                "balance_mean":float(np.mean(feat["balance"],dtype=np.float64)),
                "hr_sha256":sha256_array(hr),"lr_sha256":sha256_array(lr),
            }
            rows.append(row)
            manifest.append({"case_id":case_id,"family":family,"group":group,"generator":fn.__name__,"variant":i,"hr_sha256":row["hr_sha256"],"lr_sha256":row["lr_sha256"]})
            print(case_id, f"gap={row['gap_v01_db']:+.6f} dB", f"gate={row['gate_mean']:.6f}")

    structural=[r for r in rows if r["family"] in STRUCTURAL_FAMILIES]
    texture=[r for r in rows if r["family"] in TEXTURE_FAMILIES]
    allb=block(rows); sb=block(structural); tb=block(texture)
    checks={
        "overall_mean":allb["mean_gap_v01_db"]>=GATES["overall_mean_gap_v01_db_min"],
        "overall_worst":allb["worst_gap_v01_db"]>=GATES["overall_worst_gap_v01_db_min"],
        "structural_mean":sb["mean_gap_v01_db"]>=GATES["structural_mean_gap_v01_db_min"],
        "structural_worst":sb["worst_gap_v01_db"]>=GATES["structural_worst_gap_v01_db_min"],
        "texture_mean":tb["mean_gap_v01_db"]>=GATES["texture_mean_gap_v01_db_min"],
    }
    passed=all(checks.values())
    summary={
        "protocol":"LAB16_POST_FREEZE_FRESH_VALIDATION",
        "status":"PASS" if passed else "FAIL",
        "validation_not_tuning":True,
        "fresh_generator_authored_after_freeze":True,
        "old_c_used":False,
        "seed":SEED,
        "case_count":len(rows),
        "scale":SCALE,
        "hr_size":[HR_W,HR_H],"lr_size":[LR_W,LR_H],
        "input_generation":{"library":"scikit-image","version":skimage.__version__,"function":"skimage.transform.resize","order":3,"mode":"reflect","anti_aliasing":True,"preserve_range":True,"clip":True,"domain":"sRGB/code values (not linearized)"},
        "frozen_candidate_file_sha256":frozen_sha256,
        "frozen_candidate":frozen,
        "precommitted_gates":GATES,
        "checks":checks,
        "all":allb,"structural":sb,"texture_frequency":tb,
        "family_blocks":{fam:block([r for r in rows if r["family"]==fam]) for fam,_,_ in GENERATORS},
        "post_observation_rule":"Do not tune LAB15 parameters or LAB16 thresholds/generator against this result. Failure rejects this frozen candidate; subsequent candidates require a newly authored untouched validation corpus.",
    }
    write_csv(out/"PER_CASE.csv",rows)
    (out/"CORPUS_MANIFEST.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    (out/"SUMMARY.json").write_text(json.dumps(summary,indent=2)+"\n",encoding="utf-8")
    print(json.dumps(summary,indent=2))
    raise SystemExit(0 if passed else 2)

if __name__=="__main__":
    main()
